version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "6666:9000"   
      - "7777:9001"    
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1qaz2wsx
    volumes:
      - minio_data:/data

  minio_init:
    image: minio/mc:latest
    container_name: minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 admin 1qaz2wsx &&
      mc mb local/vedro-s-datoy || true &&
      gzip -d -k /data/vedro-s-datoy/players.csv.gz &&
      mc cp /data/vedro-s-datoy/*.csv local/vedro-s-datoy/
      "
    volumes:
      - ./minio_data:/data

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter
    ports:
      - "1337:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh /home/jovyan/work/cs-go-was-astralis-cheating-all-along.ipynb
    depends_on:
      - minio

volumes:
  minio_data:

