version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "6666:9000"
      - "7777:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1qaz2wsx
    volumes:
      - minio_data:/data

  minio_init:
    image: minio/mc:latest
    container_name: minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 admin 1qaz2wsx &&
      mc mb local/vedro-s-datoy || true &&
      mc cp /data/anime-dataset-2023.csv local/vedro-s-datoy/
      "
    volumes:
      - ./data:/data

  jupyter:
    build: .
    container_name: jupyter
    ports:
      - "1337:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data
    command: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - minio_init

volumes:
  minio_data:
