version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # API порт
      - "9001:9001"  # UI порт
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    networks:
      - s3-jupyter-network

  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./jupyter:/home/jovyan/work
      - ./data:/data
    networks:
      - s3-jupyter-network
    depends_on:
      - minio

networks:
  s3-jupyter-network:
    driver: bridge
